# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CSM37F58_APP.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(660, 879)
        MainWindow.setMinimumSize(QtCore.QSize(400, 500))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        MainWindow.setFont(font)
        MainWindow.setWindowOpacity(1.0)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(0, 0))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(204, 204, 204))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(204, 204, 204))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(204, 204, 204))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(204, 204, 204))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.tabWidget.setPalette(palette)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_update_all = QtWidgets.QPushButton(self.tab_2)
        self.btn_update_all.setObjectName("btn_update_all")
        self.horizontalLayout.addWidget(self.btn_update_all)
        self.horizontalLayout.setStretch(0, 1)
        self.gridLayout_2.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.tabWidget_2 = QtWidgets.QTabWidget(self.tab_2)
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab_4)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.watch_table_dev_set = QtWidgets.QTableView(self.tab_4)
        self.watch_table_dev_set.setMouseTracking(True)
        self.watch_table_dev_set.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.watch_table_dev_set.setEditTriggers(QtWidgets.QAbstractItemView.AnyKeyPressed|QtWidgets.QAbstractItemView.DoubleClicked|QtWidgets.QAbstractItemView.EditKeyPressed|QtWidgets.QAbstractItemView.SelectedClicked)
        self.watch_table_dev_set.setDragEnabled(False)
        self.watch_table_dev_set.setDragDropMode(QtWidgets.QAbstractItemView.DragOnly)
        self.watch_table_dev_set.setAlternatingRowColors(True)
        self.watch_table_dev_set.setSortingEnabled(False)
        self.watch_table_dev_set.setObjectName("watch_table_dev_set")
        self.watch_table_dev_set.horizontalHeader().setDefaultSectionSize(150)
        self.watch_table_dev_set.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout_2.addWidget(self.watch_table_dev_set)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        self.gridLayout_3.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.tabWidget_2.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.tab_5)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.watch_table_dev_info = QtWidgets.QTableView(self.tab_5)
        self.watch_table_dev_info.setMouseTracking(True)
        self.watch_table_dev_info.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.watch_table_dev_info.setEditTriggers(QtWidgets.QAbstractItemView.AnyKeyPressed|QtWidgets.QAbstractItemView.DoubleClicked|QtWidgets.QAbstractItemView.EditKeyPressed|QtWidgets.QAbstractItemView.SelectedClicked)
        self.watch_table_dev_info.setDragEnabled(False)
        self.watch_table_dev_info.setDragDropMode(QtWidgets.QAbstractItemView.DragOnly)
        self.watch_table_dev_info.setAlternatingRowColors(True)
        self.watch_table_dev_info.setSortingEnabled(False)
        self.watch_table_dev_info.setObjectName("watch_table_dev_info")
        self.watch_table_dev_info.horizontalHeader().setDefaultSectionSize(150)
        self.watch_table_dev_info.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout_5.addWidget(self.watch_table_dev_info)
        self.gridLayout_7.addLayout(self.verticalLayout_5, 0, 0, 1, 1)
        self.tabWidget_2.addTab(self.tab_5, "")
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tab_8)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.watch_table_usr_info = QtWidgets.QTableView(self.tab_8)
        self.watch_table_usr_info.setMouseTracking(True)
        self.watch_table_usr_info.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.watch_table_usr_info.setEditTriggers(QtWidgets.QAbstractItemView.AnyKeyPressed|QtWidgets.QAbstractItemView.DoubleClicked|QtWidgets.QAbstractItemView.EditKeyPressed|QtWidgets.QAbstractItemView.SelectedClicked)
        self.watch_table_usr_info.setDragEnabled(False)
        self.watch_table_usr_info.setDragDropMode(QtWidgets.QAbstractItemView.DragOnly)
        self.watch_table_usr_info.setAlternatingRowColors(True)
        self.watch_table_usr_info.setSortingEnabled(False)
        self.watch_table_usr_info.setObjectName("watch_table_usr_info")
        self.watch_table_usr_info.horizontalHeader().setDefaultSectionSize(150)
        self.watch_table_usr_info.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout_6.addWidget(self.watch_table_usr_info)
        self.gridLayout_5.addLayout(self.verticalLayout_6, 0, 0, 1, 1)
        self.tabWidget_2.addTab(self.tab_8, "")
        self.tab_9 = QtWidgets.QWidget()
        self.tab_9.setObjectName("tab_9")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.tab_9)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.watch_table_usr_bia = QtWidgets.QTableView(self.tab_9)
        self.watch_table_usr_bia.setMouseTracking(True)
        self.watch_table_usr_bia.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.watch_table_usr_bia.setEditTriggers(QtWidgets.QAbstractItemView.AnyKeyPressed|QtWidgets.QAbstractItemView.DoubleClicked|QtWidgets.QAbstractItemView.EditKeyPressed|QtWidgets.QAbstractItemView.SelectedClicked)
        self.watch_table_usr_bia.setDragEnabled(False)
        self.watch_table_usr_bia.setDragDropMode(QtWidgets.QAbstractItemView.DragOnly)
        self.watch_table_usr_bia.setAlternatingRowColors(True)
        self.watch_table_usr_bia.setSortingEnabled(False)
        self.watch_table_usr_bia.setObjectName("watch_table_usr_bia")
        self.watch_table_usr_bia.horizontalHeader().setDefaultSectionSize(150)
        self.watch_table_usr_bia.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout_7.addWidget(self.watch_table_usr_bia)
        self.gridLayout_6.addLayout(self.verticalLayout_7, 0, 0, 1, 1)
        self.tabWidget_2.addTab(self.tab_9, "")
        self.gridLayout_2.addWidget(self.tabWidget_2, 1, 0, 1, 1)
        self.tabWidget_3 = QtWidgets.QTabWidget(self.tab_2)
        self.tabWidget_3.setObjectName("tabWidget_3")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.tab_6)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.watch_table_analy_result = QtWidgets.QTableView(self.tab_6)
        self.watch_table_analy_result.setMouseTracking(True)
        self.watch_table_analy_result.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.watch_table_analy_result.setEditTriggers(QtWidgets.QAbstractItemView.AnyKeyPressed|QtWidgets.QAbstractItemView.DoubleClicked|QtWidgets.QAbstractItemView.EditKeyPressed|QtWidgets.QAbstractItemView.SelectedClicked)
        self.watch_table_analy_result.setDragEnabled(False)
        self.watch_table_analy_result.setDragDropMode(QtWidgets.QAbstractItemView.DragOnly)
        self.watch_table_analy_result.setAlternatingRowColors(True)
        self.watch_table_analy_result.setSortingEnabled(False)
        self.watch_table_analy_result.setObjectName("watch_table_analy_result")
        self.watch_table_analy_result.horizontalHeader().setDefaultSectionSize(150)
        self.watch_table_analy_result.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout_4.addWidget(self.watch_table_analy_result)
        self.gridLayout_8.addLayout(self.verticalLayout_4, 0, 0, 1, 1)
        self.tabWidget_3.addTab(self.tab_6, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.tab_7)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.watch_table_tst_middle = QtWidgets.QTableView(self.tab_7)
        self.watch_table_tst_middle.setMouseTracking(True)
        self.watch_table_tst_middle.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.watch_table_tst_middle.setEditTriggers(QtWidgets.QAbstractItemView.AnyKeyPressed|QtWidgets.QAbstractItemView.DoubleClicked|QtWidgets.QAbstractItemView.EditKeyPressed|QtWidgets.QAbstractItemView.SelectedClicked)
        self.watch_table_tst_middle.setDragEnabled(False)
        self.watch_table_tst_middle.setDragDropMode(QtWidgets.QAbstractItemView.DragOnly)
        self.watch_table_tst_middle.setAlternatingRowColors(True)
        self.watch_table_tst_middle.setSortingEnabled(False)
        self.watch_table_tst_middle.setObjectName("watch_table_tst_middle")
        self.watch_table_tst_middle.horizontalHeader().setDefaultSectionSize(150)
        self.watch_table_tst_middle.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout_8.addWidget(self.watch_table_tst_middle)
        self.gridLayout_9.addLayout(self.verticalLayout_8, 0, 0, 1, 1)
        self.tabWidget_3.addTab(self.tab_7, "")
        self.tab_10 = QtWidgets.QWidget()
        self.tab_10.setObjectName("tab_10")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.tab_10)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.watch_table_com_log = QtWidgets.QTableView(self.tab_10)
        self.watch_table_com_log.setMouseTracking(True)
        self.watch_table_com_log.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.watch_table_com_log.setEditTriggers(QtWidgets.QAbstractItemView.AnyKeyPressed|QtWidgets.QAbstractItemView.DoubleClicked|QtWidgets.QAbstractItemView.EditKeyPressed|QtWidgets.QAbstractItemView.SelectedClicked)
        self.watch_table_com_log.setDragEnabled(False)
        self.watch_table_com_log.setDragDropMode(QtWidgets.QAbstractItemView.DragOnly)
        self.watch_table_com_log.setAlternatingRowColors(True)
        self.watch_table_com_log.setSortingEnabled(False)
        self.watch_table_com_log.setObjectName("watch_table_com_log")
        self.watch_table_com_log.horizontalHeader().setDefaultSectionSize(150)
        self.watch_table_com_log.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout_9.addWidget(self.watch_table_com_log)
        self.gridLayout_10.addLayout(self.verticalLayout_9, 0, 0, 1, 1)
        self.tabWidget_3.addTab(self.tab_10, "")
        self.tab_11 = QtWidgets.QWidget()
        self.tab_11.setObjectName("tab_11")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.tab_11)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.watch_table_res_real = QtWidgets.QTableView(self.tab_11)
        self.watch_table_res_real.setMouseTracking(True)
        self.watch_table_res_real.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.watch_table_res_real.setEditTriggers(QtWidgets.QAbstractItemView.AnyKeyPressed|QtWidgets.QAbstractItemView.DoubleClicked|QtWidgets.QAbstractItemView.EditKeyPressed|QtWidgets.QAbstractItemView.SelectedClicked)
        self.watch_table_res_real.setDragEnabled(False)
        self.watch_table_res_real.setDragDropMode(QtWidgets.QAbstractItemView.DragOnly)
        self.watch_table_res_real.setAlternatingRowColors(True)
        self.watch_table_res_real.setSortingEnabled(False)
        self.watch_table_res_real.setObjectName("watch_table_res_real")
        self.watch_table_res_real.horizontalHeader().setDefaultSectionSize(150)
        self.watch_table_res_real.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout_3.addWidget(self.watch_table_res_real)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.tabWidget_3.addTab(self.tab_11, "")
        self.gridLayout_2.addWidget(self.tabWidget_3, 2, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.formLayout = QtWidgets.QFormLayout(self.tab)
        self.formLayout.setObjectName("formLayout")
        self.checkBox = QtWidgets.QCheckBox(self.tab)
        self.checkBox.setEnabled(False)
        self.checkBox.setObjectName("checkBox")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.checkBox)
        self.label_6 = QtWidgets.QLabel(self.tab)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.label_6.setPalette(palette)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label_6)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.line_cmd_1 = QtWidgets.QLineEdit(self.tab)
        self.line_cmd_1.setEnabled(False)
        self.line_cmd_1.setAccessibleDescription("")
        self.line_cmd_1.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.line_cmd_1.setObjectName("line_cmd_1")
        self.horizontalLayout_9.addWidget(self.line_cmd_1)
        self.btn_cmd_1 = QtWidgets.QPushButton(self.tab)
        self.btn_cmd_1.setAccessibleDescription("")
        self.btn_cmd_1.setCheckable(False)
        self.btn_cmd_1.setObjectName("btn_cmd_1")
        self.horizontalLayout_9.addWidget(self.btn_cmd_1)
        self.horizontalLayout_9.setStretch(0, 6)
        self.horizontalLayout_9.setStretch(1, 1)
        self.formLayout.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_9)
        self.checkBox_2 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_2.setEnabled(False)
        self.checkBox_2.setObjectName("checkBox_2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.checkBox_2)
        self.label_7 = QtWidgets.QLabel(self.tab)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.label_7)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.line_cmd_2 = QtWidgets.QLineEdit(self.tab)
        self.line_cmd_2.setEnabled(False)
        self.line_cmd_2.setAccessibleDescription("")
        self.line_cmd_2.setObjectName("line_cmd_2")
        self.horizontalLayout_10.addWidget(self.line_cmd_2)
        self.btn_cmd_2 = QtWidgets.QPushButton(self.tab)
        self.btn_cmd_2.setAccessibleDescription("")
        self.btn_cmd_2.setObjectName("btn_cmd_2")
        self.horizontalLayout_10.addWidget(self.btn_cmd_2)
        self.horizontalLayout_10.setStretch(0, 6)
        self.horizontalLayout_10.setStretch(1, 1)
        self.formLayout.setLayout(3, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_10)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_2.setEnabled(False)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_8.addWidget(self.lineEdit_2)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_3.setEnabled(False)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.horizontalLayout_8.addWidget(self.lineEdit_3)
        self.lineEdit = QtWidgets.QLineEdit(self.tab)
        self.lineEdit.setEnabled(False)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_8.addWidget(self.lineEdit)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_4.setEnabled(False)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.horizontalLayout_8.addWidget(self.lineEdit_4)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_5.setEnabled(False)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.horizontalLayout_8.addWidget(self.lineEdit_5)
        self.formLayout.setLayout(4, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_8)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.line_body_height = QtWidgets.QLineEdit(self.tab)
        self.line_body_height.setObjectName("line_body_height")
        self.horizontalLayout_6.addWidget(self.line_body_height)
        self.line_body_years_old = QtWidgets.QLineEdit(self.tab)
        self.line_body_years_old.setObjectName("line_body_years_old")
        self.horizontalLayout_6.addWidget(self.line_body_years_old)
        self.line_body_weight = QtWidgets.QLineEdit(self.tab)
        self.line_body_weight.setObjectName("line_body_weight")
        self.horizontalLayout_6.addWidget(self.line_body_weight)
        self.line_body_gender = QtWidgets.QLineEdit(self.tab)
        self.line_body_gender.setObjectName("line_body_gender")
        self.horizontalLayout_6.addWidget(self.line_body_gender)
        self.line_body_mode = QtWidgets.QLineEdit(self.tab)
        self.line_body_mode.setEnabled(False)
        self.line_body_mode.setObjectName("line_body_mode")
        self.horizontalLayout_6.addWidget(self.line_body_mode)
        self.horizontalLayout_6.setStretch(0, 1)
        self.horizontalLayout_6.setStretch(1, 1)
        self.horizontalLayout_6.setStretch(2, 1)
        self.horizontalLayout_6.setStretch(3, 1)
        self.horizontalLayout_6.setStretch(4, 1)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_6)
        self.formLayout.setLayout(5, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_4)
        self.checkBox_3 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_3.setEnabled(False)
        self.checkBox_3.setObjectName("checkBox_3")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.checkBox_3)
        self.label_9 = QtWidgets.QLabel(self.tab)
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.label_9)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.line_cmd_3 = QtWidgets.QLineEdit(self.tab)
        self.line_cmd_3.setEnabled(False)
        self.line_cmd_3.setAccessibleDescription("")
        self.line_cmd_3.setObjectName("line_cmd_3")
        self.horizontalLayout_11.addWidget(self.line_cmd_3)
        self.btn_cmd_3 = QtWidgets.QPushButton(self.tab)
        self.btn_cmd_3.setAccessibleDescription("")
        self.btn_cmd_3.setObjectName("btn_cmd_3")
        self.horizontalLayout_11.addWidget(self.btn_cmd_3)
        self.horizontalLayout_11.setStretch(0, 6)
        self.horizontalLayout_11.setStretch(1, 1)
        self.formLayout.setLayout(7, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_11)
        self.checkBox_8 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_8.setEnabled(False)
        self.checkBox_8.setObjectName("checkBox_8")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.checkBox_8)
        self.label_8 = QtWidgets.QLabel(self.tab)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.label_8)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.line_cmd_4 = QtWidgets.QLineEdit(self.tab)
        self.line_cmd_4.setEnabled(False)
        self.line_cmd_4.setAccessibleDescription("")
        self.line_cmd_4.setObjectName("line_cmd_4")
        self.horizontalLayout_12.addWidget(self.line_cmd_4)
        self.btn_cmd_4 = QtWidgets.QPushButton(self.tab)
        self.btn_cmd_4.setAccessibleDescription("")
        self.btn_cmd_4.setObjectName("btn_cmd_4")
        self.horizontalLayout_12.addWidget(self.btn_cmd_4)
        self.horizontalLayout_12.setStretch(0, 6)
        self.horizontalLayout_12.setStretch(1, 1)
        self.formLayout.setLayout(9, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_12)
        self.checkBox_9 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_9.setEnabled(False)
        self.checkBox_9.setObjectName("checkBox_9")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.checkBox_9)
        self.label_10 = QtWidgets.QLabel(self.tab)
        self.label_10.setObjectName("label_10")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.label_10)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.line_cmd_5 = QtWidgets.QLineEdit(self.tab)
        self.line_cmd_5.setEnabled(False)
        self.line_cmd_5.setAccessibleDescription("")
        self.line_cmd_5.setObjectName("line_cmd_5")
        self.horizontalLayout_13.addWidget(self.line_cmd_5)
        self.btn_cmd_5 = QtWidgets.QPushButton(self.tab)
        self.btn_cmd_5.setAccessibleDescription("")
        self.btn_cmd_5.setObjectName("btn_cmd_5")
        self.horizontalLayout_13.addWidget(self.btn_cmd_5)
        self.horizontalLayout_13.setStretch(0, 6)
        self.horizontalLayout_13.setStretch(1, 1)
        self.formLayout.setLayout(11, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_13)
        self.checkBox_7 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_7.setEnabled(False)
        self.checkBox_7.setObjectName("checkBox_7")
        self.formLayout.setWidget(12, QtWidgets.QFormLayout.LabelRole, self.checkBox_7)
        self.label_11 = QtWidgets.QLabel(self.tab)
        self.label_11.setObjectName("label_11")
        self.formLayout.setWidget(12, QtWidgets.QFormLayout.FieldRole, self.label_11)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.line_cmd_6 = QtWidgets.QLineEdit(self.tab)
        self.line_cmd_6.setEnabled(False)
        self.line_cmd_6.setAccessibleDescription("")
        self.line_cmd_6.setObjectName("line_cmd_6")
        self.horizontalLayout_14.addWidget(self.line_cmd_6)
        self.btn_cmd_6 = QtWidgets.QPushButton(self.tab)
        self.btn_cmd_6.setAccessibleDescription("")
        self.btn_cmd_6.setObjectName("btn_cmd_6")
        self.horizontalLayout_14.addWidget(self.btn_cmd_6)
        self.horizontalLayout_14.setStretch(0, 6)
        self.horizontalLayout_14.setStretch(1, 1)
        self.formLayout.setLayout(13, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_14)
        self.checkBox_6 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_6.setEnabled(False)
        self.checkBox_6.setObjectName("checkBox_6")
        self.formLayout.setWidget(14, QtWidgets.QFormLayout.LabelRole, self.checkBox_6)
        self.label_12 = QtWidgets.QLabel(self.tab)
        self.label_12.setObjectName("label_12")
        self.formLayout.setWidget(14, QtWidgets.QFormLayout.FieldRole, self.label_12)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.line_cmd_7 = QtWidgets.QLineEdit(self.tab)
        self.line_cmd_7.setEnabled(True)
        self.line_cmd_7.setAccessibleDescription("")
        self.line_cmd_7.setObjectName("line_cmd_7")
        self.horizontalLayout_15.addWidget(self.line_cmd_7)
        self.btn_cmd_7 = QtWidgets.QPushButton(self.tab)
        self.btn_cmd_7.setAccessibleDescription("")
        self.btn_cmd_7.setObjectName("btn_cmd_7")
        self.horizontalLayout_15.addWidget(self.btn_cmd_7)
        self.horizontalLayout_15.setStretch(0, 6)
        self.horizontalLayout_15.setStretch(1, 1)
        self.formLayout.setLayout(15, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_15)
        self.checkBox_10 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_10.setEnabled(False)
        self.checkBox_10.setObjectName("checkBox_10")
        self.formLayout.setWidget(16, QtWidgets.QFormLayout.LabelRole, self.checkBox_10)
        self.label_13 = QtWidgets.QLabel(self.tab)
        self.label_13.setObjectName("label_13")
        self.formLayout.setWidget(16, QtWidgets.QFormLayout.FieldRole, self.label_13)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.line_cmd_8 = QtWidgets.QLineEdit(self.tab)
        self.line_cmd_8.setEnabled(False)
        self.line_cmd_8.setAccessibleDescription("")
        self.line_cmd_8.setObjectName("line_cmd_8")
        self.horizontalLayout_17.addWidget(self.line_cmd_8)
        self.btn_cmd_8 = QtWidgets.QPushButton(self.tab)
        self.btn_cmd_8.setAccessibleDescription("")
        self.btn_cmd_8.setObjectName("btn_cmd_8")
        self.horizontalLayout_17.addWidget(self.btn_cmd_8)
        self.horizontalLayout_17.setStretch(0, 6)
        self.horizontalLayout_17.setStretch(1, 1)
        self.formLayout.setLayout(17, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_17)
        self.checkBox_13 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_13.setEnabled(False)
        self.checkBox_13.setObjectName("checkBox_13")
        self.formLayout.setWidget(18, QtWidgets.QFormLayout.LabelRole, self.checkBox_13)
        self.label_16 = QtWidgets.QLabel(self.tab)
        self.label_16.setObjectName("label_16")
        self.formLayout.setWidget(18, QtWidgets.QFormLayout.FieldRole, self.label_16)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.line_cmd_9 = QtWidgets.QLineEdit(self.tab)
        self.line_cmd_9.setEnabled(False)
        self.line_cmd_9.setAccessibleDescription("")
        self.line_cmd_9.setObjectName("line_cmd_9")
        self.horizontalLayout_19.addWidget(self.line_cmd_9)
        self.btn_cmd_9 = QtWidgets.QPushButton(self.tab)
        self.btn_cmd_9.setAccessibleDescription("")
        self.btn_cmd_9.setObjectName("btn_cmd_9")
        self.horizontalLayout_19.addWidget(self.btn_cmd_9)
        self.horizontalLayout_19.setStretch(0, 6)
        self.horizontalLayout_19.setStretch(1, 1)
        self.formLayout.setLayout(19, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_19)
        self.checkBox_14 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_14.setEnabled(False)
        self.checkBox_14.setObjectName("checkBox_14")
        self.formLayout.setWidget(20, QtWidgets.QFormLayout.LabelRole, self.checkBox_14)
        self.label_17 = QtWidgets.QLabel(self.tab)
        self.label_17.setObjectName("label_17")
        self.formLayout.setWidget(20, QtWidgets.QFormLayout.FieldRole, self.label_17)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.line_cmd_query = QtWidgets.QLineEdit(self.tab)
        self.line_cmd_query.setEnabled(False)
        self.line_cmd_query.setAccessibleDescription("")
        self.line_cmd_query.setObjectName("line_cmd_query")
        self.horizontalLayout_16.addWidget(self.line_cmd_query)
        self.line_cmd_query_dis = QtWidgets.QLineEdit(self.tab)
        self.line_cmd_query_dis.setObjectName("line_cmd_query_dis")
        self.horizontalLayout_16.addWidget(self.line_cmd_query_dis)
        self.horizontalLayout_20.addLayout(self.horizontalLayout_16)
        self.btn_cmd_query = QtWidgets.QPushButton(self.tab)
        self.btn_cmd_query.setAccessibleDescription("")
        self.btn_cmd_query.setObjectName("btn_cmd_query")
        self.horizontalLayout_20.addWidget(self.btn_cmd_query)
        self.horizontalLayout_20.setStretch(0, 6)
        self.horizontalLayout_20.setStretch(1, 1)
        self.formLayout.setLayout(21, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_20)
        self.checkBox_16 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_16.setEnabled(False)
        self.checkBox_16.setObjectName("checkBox_16")
        self.formLayout.setWidget(22, QtWidgets.QFormLayout.LabelRole, self.checkBox_16)
        self.label_19 = QtWidgets.QLabel(self.tab)
        self.label_19.setObjectName("label_19")
        self.formLayout.setWidget(22, QtWidgets.QFormLayout.FieldRole, self.label_19)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.line_cmd_write = QtWidgets.QLineEdit(self.tab)
        self.line_cmd_write.setEnabled(True)
        self.line_cmd_write.setAccessibleDescription("")
        self.line_cmd_write.setObjectName("line_cmd_write")
        self.horizontalLayout_22.addWidget(self.line_cmd_write)
        self.btn_cmd_write = QtWidgets.QPushButton(self.tab)
        self.btn_cmd_write.setAccessibleDescription("")
        self.btn_cmd_write.setObjectName("btn_cmd_write")
        self.horizontalLayout_22.addWidget(self.btn_cmd_write)
        self.horizontalLayout_22.setStretch(0, 6)
        self.horizontalLayout_22.setStretch(1, 1)
        self.formLayout.setLayout(23, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_22)
        self.checkBox_11 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_11.setEnabled(False)
        self.checkBox_11.setObjectName("checkBox_11")
        self.formLayout.setWidget(24, QtWidgets.QFormLayout.LabelRole, self.checkBox_11)
        self.label_14 = QtWidgets.QLabel(self.tab)
        self.label_14.setObjectName("label_14")
        self.formLayout.setWidget(24, QtWidgets.QFormLayout.FieldRole, self.label_14)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.line_cmd_read = QtWidgets.QLineEdit(self.tab)
        self.line_cmd_read.setEnabled(True)
        self.line_cmd_read.setAccessibleDescription("")
        self.line_cmd_read.setObjectName("line_cmd_read")
        self.horizontalLayout_3.addWidget(self.line_cmd_read)
        self.line_cmd_read_dis = QtWidgets.QLineEdit(self.tab)
        self.line_cmd_read_dis.setObjectName("line_cmd_read_dis")
        self.horizontalLayout_3.addWidget(self.line_cmd_read_dis)
        self.horizontalLayout_18.addLayout(self.horizontalLayout_3)
        self.btn_cmd_read = QtWidgets.QPushButton(self.tab)
        self.btn_cmd_read.setAccessibleDescription("")
        self.btn_cmd_read.setObjectName("btn_cmd_read")
        self.horizontalLayout_18.addWidget(self.btn_cmd_read)
        self.horizontalLayout_18.setStretch(0, 6)
        self.horizontalLayout_18.setStretch(1, 1)
        self.formLayout.setLayout(25, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_18)
        self.checkBox_12 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_12.setEnabled(False)
        self.checkBox_12.setObjectName("checkBox_12")
        self.formLayout.setWidget(26, QtWidgets.QFormLayout.LabelRole, self.checkBox_12)
        self.label_15 = QtWidgets.QLabel(self.tab)
        self.label_15.setObjectName("label_15")
        self.formLayout.setWidget(26, QtWidgets.QFormLayout.FieldRole, self.label_15)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.btn_query_state = QtWidgets.QPushButton(self.tab)
        self.btn_query_state.setObjectName("btn_query_state")
        self.horizontalLayout_5.addWidget(self.btn_query_state)
        self.btn_cmd_reset = QtWidgets.QPushButton(self.tab)
        self.btn_cmd_reset.setObjectName("btn_cmd_reset")
        self.horizontalLayout_5.addWidget(self.btn_cmd_reset)
        self.horizontalLayout_5.setStretch(0, 6)
        self.horizontalLayout_5.setStretch(1, 1)
        self.formLayout.setLayout(27, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_5)
        self.checkBox.raise_()
        self.label_6.raise_()
        self.checkBox_2.raise_()
        self.label_7.raise_()
        self.checkBox_3.raise_()
        self.label_9.raise_()
        self.checkBox_8.raise_()
        self.label_8.raise_()
        self.checkBox_9.raise_()
        self.label_10.raise_()
        self.checkBox_7.raise_()
        self.label_11.raise_()
        self.checkBox_6.raise_()
        self.label_12.raise_()
        self.checkBox_10.raise_()
        self.label_13.raise_()
        self.checkBox_11.raise_()
        self.label_14.raise_()
        self.checkBox_12.raise_()
        self.label_15.raise_()
        self.checkBox_13.raise_()
        self.label_16.raise_()
        self.checkBox_14.raise_()
        self.label_17.raise_()
        self.checkBox_16.raise_()
        self.label_19.raise_()
        self.tabWidget.addTab(self.tab, "")
        self.tab_12 = QtWidgets.QWidget()
        self.tab_12.setObjectName("tab_12")
        self.gridLayout = QtWidgets.QGridLayout(self.tab_12)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.tab_12)
        self.lineEdit_8.setEnabled(False)
        self.lineEdit_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.horizontalLayout_24.addWidget(self.lineEdit_8)
        self.line_timer_read_addr = QtWidgets.QLineEdit(self.tab_12)
        self.line_timer_read_addr.setObjectName("line_timer_read_addr")
        self.horizontalLayout_24.addWidget(self.line_timer_read_addr)
        self.horizontalLayout_24.setStretch(0, 2)
        self.horizontalLayout_24.setStretch(1, 1)
        self.verticalLayout_11.addLayout(self.horizontalLayout_24)
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.tab_12)
        self.lineEdit_9.setEnabled(False)
        self.lineEdit_9.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.horizontalLayout_25.addWidget(self.lineEdit_9)
        self.line_timer_read_byte_len = QtWidgets.QLineEdit(self.tab_12)
        self.line_timer_read_byte_len.setObjectName("line_timer_read_byte_len")
        self.horizontalLayout_25.addWidget(self.line_timer_read_byte_len)
        self.horizontalLayout_25.setStretch(0, 2)
        self.horizontalLayout_25.setStretch(1, 1)
        self.verticalLayout_11.addLayout(self.horizontalLayout_25)
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.tab_12)
        self.lineEdit_6.setEnabled(False)
        self.lineEdit_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.horizontalLayout_26.addWidget(self.lineEdit_6)
        self.line_read_time = QtWidgets.QLineEdit(self.tab_12)
        self.line_read_time.setObjectName("line_read_time")
        self.horizontalLayout_26.addWidget(self.line_read_time)
        self.horizontalLayout_26.setStretch(0, 2)
        self.horizontalLayout_26.setStretch(1, 1)
        self.verticalLayout_11.addLayout(self.horizontalLayout_26)
        self.horizontalLayout_23.addLayout(self.verticalLayout_11)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.comboBox_read_timer = QtWidgets.QComboBox(self.tab_12)
        self.comboBox_read_timer.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.comboBox_read_timer.setObjectName("comboBox_read_timer")
        self.verticalLayout_12.addWidget(self.comboBox_read_timer)
        self.btn_read_timer = QtWidgets.QPushButton(self.tab_12)
        self.btn_read_timer.setObjectName("btn_read_timer")
        self.verticalLayout_12.addWidget(self.btn_read_timer)
        self.horizontalLayout_23.addLayout(self.verticalLayout_12)
        self.horizontalLayout_23.setStretch(0, 2)
        self.horizontalLayout_23.setStretch(1, 1)
        self.gridLayout.addLayout(self.horizontalLayout_23, 0, 0, 1, 1)
        self.plainTextEdit_read_timer = QtWidgets.QPlainTextEdit(self.tab_12)
        self.plainTextEdit_read_timer.setObjectName("plainTextEdit_read_timer")
        self.gridLayout.addWidget(self.plainTextEdit_read_timer, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tab_12, "")
        self.tab_13 = QtWidgets.QWidget()
        self.tab_13.setObjectName("tab_13")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.tab_13)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.textBrowser_iap = QtWidgets.QTextBrowser(self.tab_13)
        self.textBrowser_iap.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.textBrowser_iap.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.textBrowser_iap.setObjectName("textBrowser_iap")
        self.horizontalLayout_21.addWidget(self.textBrowser_iap)
        self.textBrowser_iap_read = QtWidgets.QTextBrowser(self.tab_13)
        self.textBrowser_iap_read.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.textBrowser_iap_read.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.textBrowser_iap_read.setObjectName("textBrowser_iap_read")
        self.horizontalLayout_21.addWidget(self.textBrowser_iap_read)
        self.verticalLayout_10.addLayout(self.horizontalLayout_21)
        self.btn_iap_loadfile = QtWidgets.QPushButton(self.tab_13)
        self.btn_iap_loadfile.setObjectName("btn_iap_loadfile")
        self.verticalLayout_10.addWidget(self.btn_iap_loadfile)
        self.btn_iap_erase = QtWidgets.QPushButton(self.tab_13)
        self.btn_iap_erase.setObjectName("btn_iap_erase")
        self.verticalLayout_10.addWidget(self.btn_iap_erase)
        self.btn_iap_start = QtWidgets.QPushButton(self.tab_13)
        self.btn_iap_start.setEnabled(False)
        self.btn_iap_start.setObjectName("btn_iap_start")
        self.verticalLayout_10.addWidget(self.btn_iap_start)
        self.btn_iap_read_flash = QtWidgets.QPushButton(self.tab_13)
        self.btn_iap_read_flash.setEnabled(False)
        self.btn_iap_read_flash.setObjectName("btn_iap_read_flash")
        self.verticalLayout_10.addWidget(self.btn_iap_read_flash)
        self.btn_iap_get_version = QtWidgets.QPushButton(self.tab_13)
        self.btn_iap_get_version.setObjectName("btn_iap_get_version")
        self.verticalLayout_10.addWidget(self.btn_iap_get_version)
        self.tabWidget.addTab(self.tab_13, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.textEdit = QtWidgets.QTextEdit(self.tab_3)
        font = QtGui.QFont()
        font.setFamily("宋体")
        self.textEdit.setFont(font)
        self.textEdit.setReadOnly(True)
        self.textEdit.setObjectName("textEdit")
        self.gridLayout_4.addWidget(self.textEdit, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_3, "")
        self.horizontalLayout_7.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 660, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(4)
        self.tabWidget_2.setCurrentIndex(3)
        self.tabWidget_3.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "CSM37F58-八电极模块测试上位机"))
        self.btn_update_all.setText(_translate("MainWindow", "点击更新全部RAM"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_4), _translate("MainWindow", "设备配置区（读/写）"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_5), _translate("MainWindow", "设备信息区（读）"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_8), _translate("MainWindow", "用户信息区（读/写）"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_9), _translate("MainWindow", "用户测试BIA区（读）"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_6), _translate("MainWindow", "成分分析结果区（读）"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_7), _translate("MainWindow", "测试过程数据区（读）"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_10), _translate("MainWindow", "通讯日志区（读）"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_11), _translate("MainWindow", "真实电阻显示区（读）"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "各片区RAM(读/写)"))
        self.checkBox.setText(_translate("MainWindow", "1"))
        self.label_6.setText(_translate("MainWindow", "WakeUp命令"))
        self.line_cmd_1.setText(_translate("MainWindow", "0xA0 0x3F 0x5A 0x53"))
        self.btn_cmd_1.setToolTip(_translate("MainWindow", "发送此命令，唤醒模组"))
        self.btn_cmd_1.setText(_translate("MainWindow", "发送"))
        self.checkBox_2.setText(_translate("MainWindow", "2"))
        self.label_7.setText(_translate("MainWindow", "写入人体参数"))
        self.line_cmd_2.setText(_translate("MainWindow", "0xA0 0x10 0x58 0x02 0xC1 0xAA 0x9E 0x00"))
        self.btn_cmd_2.setToolTip(_translate("MainWindow", "直接更改，自动更新到命令（发送5次写命令）"))
        self.btn_cmd_2.setText(_translate("MainWindow", "发送"))
        self.lineEdit_2.setText(_translate("MainWindow", "身高(cm)"))
        self.lineEdit_3.setText(_translate("MainWindow", "年龄(岁)"))
        self.lineEdit.setText(_translate("MainWindow", "体重(kg)"))
        self.lineEdit_4.setText(_translate("MainWindow", "性别"))
        self.lineEdit_5.setText(_translate("MainWindow", "模式"))
        self.line_body_height.setText(_translate("MainWindow", "170"))
        self.line_body_years_old.setText(_translate("MainWindow", "30"))
        self.line_body_weight.setText(_translate("MainWindow", "70.5"))
        self.line_body_gender.setText(_translate("MainWindow", "男"))
        self.line_body_mode.setText(_translate("MainWindow", "默认"))
        self.checkBox_3.setText(_translate("MainWindow", "3"))
        self.label_9.setText(_translate("MainWindow", "使能测量开关"))
        self.line_cmd_3.setText(_translate("MainWindow", "0xA0 0x10 0x00 0x80"))
        self.btn_cmd_3.setToolTip(_translate("MainWindow", "硬件地址+发送数据地址+发送数据"))
        self.btn_cmd_3.setText(_translate("MainWindow", "发送"))
        self.checkBox_8.setText(_translate("MainWindow", "4"))
        self.label_8.setText(_translate("MainWindow", "计算成分命令"))
        self.line_cmd_4.setText(_translate("MainWindow", "0xA0 0x3F 0x5A 0x04"))
        self.btn_cmd_4.setToolTip(_translate("MainWindow", "硬件地址+发送数据地址+发送数据"))
        self.btn_cmd_4.setText(_translate("MainWindow", "发送"))
        self.checkBox_9.setText(_translate("MainWindow", "5"))
        self.label_10.setText(_translate("MainWindow", "Sleep命令（发送后不要再发命令,否则唤醒）"))
        self.line_cmd_5.setText(_translate("MainWindow", "0xA0 0x3F 0x5A 0x35"))
        self.btn_cmd_5.setToolTip(_translate("MainWindow", "硬件地址+发送数据地址+发送数据"))
        self.btn_cmd_5.setText(_translate("MainWindow", "发送"))
        self.checkBox_7.setText(_translate("MainWindow", "6"))
        self.label_11.setText(_translate("MainWindow", "写Flash命令（M_PART 和 FREQ有效）"))
        self.line_cmd_6.setText(_translate("MainWindow", "0xA0 0x3F 0x5A 0x05"))
        self.btn_cmd_6.setToolTip(_translate("MainWindow", "硬件地址+发送数据地址+发送数据"))
        self.btn_cmd_6.setText(_translate("MainWindow", "发送"))
        self.checkBox_6.setText(_translate("MainWindow", "7"))
        self.label_12.setText(_translate("MainWindow", "更改测试部位为双手，默认50KHz（需先发送写Flash命令）"))
        self.line_cmd_7.setText(_translate("MainWindow", "0xA0 0x10 0x02 0x01"))
        self.btn_cmd_7.setToolTip(_translate("MainWindow", "硬件地址+发送数据地址+发送数据"))
        self.btn_cmd_7.setText(_translate("MainWindow", "发送"))
        self.checkBox_10.setText(_translate("MainWindow", "8"))
        self.label_13.setText(_translate("MainWindow", "解锁写保护命令"))
        self.line_cmd_8.setText(_translate("MainWindow", "0xA0 0x3F 0x5A 0x06"))
        self.btn_cmd_8.setToolTip(_translate("MainWindow", "硬件地址+发送数据地址+发送数据"))
        self.btn_cmd_8.setText(_translate("MainWindow", "发送"))
        self.checkBox_13.setText(_translate("MainWindow", "9"))
        self.label_16.setText(_translate("MainWindow", "打开校准开关（需先发送解锁写保护命令）"))
        self.line_cmd_9.setText(_translate("MainWindow", "0xA0 0x10 0x09 0x80"))
        self.btn_cmd_9.setToolTip(_translate("MainWindow", "硬件地址+发送数据地址+发送数据"))
        self.btn_cmd_9.setText(_translate("MainWindow", "发送"))
        self.checkBox_14.setText(_translate("MainWindow", "10"))
        self.label_17.setText(_translate("MainWindow", "查询模块是运行在BOOT还是APP下"))
        self.line_cmd_query.setText(_translate("MainWindow", "0xA0 0xF0 0x00"))
        self.btn_cmd_query.setToolTip(_translate("MainWindow", "BOOT(启动模式：0x00), APP（正常就绪：0x01）"))
        self.btn_cmd_query.setText(_translate("MainWindow", "查询"))
        self.checkBox_16.setText(_translate("MainWindow", "11"))
        self.label_19.setText(_translate("MainWindow", "自定义写命令（写一个Byte）"))
        self.line_cmd_write.setText(_translate("MainWindow", "0xA0 0x10 0x58 0xAA"))
        self.btn_cmd_write.setToolTip(_translate("MainWindow", "硬件地址+发送数据地址+发送数据"))
        self.btn_cmd_write.setText(_translate("MainWindow", "发送"))
        self.checkBox_11.setText(_translate("MainWindow", "12"))
        self.label_14.setText(_translate("MainWindow", "自定义读命令（读取一个byte）"))
        self.line_cmd_read.setText(_translate("MainWindow", "0xA0 0x10 0x58"))
        self.btn_cmd_read.setToolTip(_translate("MainWindow", "硬件地址+读取数据地址"))
        self.btn_cmd_read.setText(_translate("MainWindow", "读取"))
        self.checkBox_12.setText(_translate("MainWindow", "13"))
        self.label_15.setText(_translate("MainWindow", "查询/复位CSM37F58"))
        self.btn_query_state.setText(_translate("MainWindow", "查询READY信号状态"))
        self.btn_cmd_reset.setToolTip(_translate("MainWindow", "显示读取到的内容"))
        self.btn_cmd_reset.setText(_translate("MainWindow", "复位"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "命令区（功能）"))
        self.lineEdit_8.setText(_translate("MainWindow", "读取地址((Base + Offset) Addr)："))
        self.line_timer_read_addr.setText(_translate("MainWindow", "0x11AC"))
        self.lineEdit_9.setText(_translate("MainWindow", "连续读取字节数（Bytes）："))
        self.line_timer_read_byte_len.setText(_translate("MainWindow", "1"))
        self.lineEdit_6.setText(_translate("MainWindow", "定时间隔时间（ms）："))
        self.line_read_time.setText(_translate("MainWindow", "1000"))
        self.btn_read_timer.setText(_translate("MainWindow", "开始"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_12), _translate("MainWindow", "定时任务"))
        self.btn_iap_loadfile.setText(_translate("MainWindow", "选择文件"))
        self.btn_iap_erase.setToolTip(_translate("MainWindow", "[0xA0, 0x00, 0x00, 0xAA, 0x55, 0xA5, 0x5A]"))
        self.btn_iap_erase.setText(_translate("MainWindow", "擦除Flash"))
        self.btn_iap_start.setToolTip(_translate("MainWindow", "先点击擦除Flash命令,会激活此按钮"))
        self.btn_iap_start.setText(_translate("MainWindow", "升级(先擦除)"))
        self.btn_iap_read_flash.setText(_translate("MainWindow", "ReadFlash(加校验区)"))
        self.btn_iap_get_version.setToolTip(_translate("MainWindow", "[0xA0, 0xFF, 0xFF, 0xA1,0xRead,0xRead,0xRead,0xRead]"))
        self.btn_iap_get_version.setText(_translate("MainWindow", "查询当前版本号（0xFFFF）"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_13), _translate("MainWindow", "在线升级（IAP）"))
        self.textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'宋体\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Consolas\';\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Consolas\';\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Consolas\'; font-size:16pt; font-weight:600;\">注意事项</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Consolas\'; font-size:16pt;\"> </span><span style=\" font-family:\'Consolas\'; font-size:12pt;\">    </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Consolas\'; font-size:16pt;\">    1. 连接示意图.</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><img src=\":/picture/img/connect_demo.png\" /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Consolas\'; font-size:16pt; font-weight:600;\">    2</span><span style=\" font-family:\'Consolas\'; font-size:12pt; font-weight:600;\">.</span><span style=\" font-family:\'Simsum\'; font-size:12pt; color:#000000;\"> 可能需要安装微软官方C++类库:</span><a href=\" https://www.microsoft.com/en-us/download/details.aspx?id=48145\"><span style=\" text-decoration: underline; color:#0000ff;\">https://www.microsoft.com/en-us/download/details.aspx?id=48145</span></a></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; text-decoration: underline; color:#0000ff;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; text-decoration: underline; color:#0000ff;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Consolas\'; font-size:16pt; font-weight:600;\">版本说明</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Consolas\'; font-size:16pt; font-weight:600;\">   </span><span style=\" font-family:\'Consolas\'; font-size:16pt; font-weight:600; font-style:italic;\">V0.4</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Consolas\'; font-size:12pt;\">     1. 增加了定时查询制定地址</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Consolas\'; font-size:12pt;\">     2. 保存对应的十进制数据到.csv文件</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Consolas\'; font-size:16pt; font-weight:600;\">   </span><span style=\" font-family:\'Consolas\'; font-size:16pt; font-weight:600; font-style:italic;\">V0.3</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Consolas\'; font-size:12pt;\">     1. 增加了IAP功能.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Consolas\'; font-size:12pt;\">     2. 查询当前版本.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Consolas\'; font-size:12pt;\">     3. 擦除Flash.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Consolas\'; font-size:12pt;\">     4. 加载bin文件.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Consolas\'; font-size:16pt; font-weight:600; font-style:italic;\">   V0.2</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Consolas\'; font-size:12pt;\">     1. 修复部分RAM读取首地址错误问题.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Consolas\'; font-size:12pt;\">     2. 发送命令时关闭按键使能.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Consolas\'; font-size:12pt;\">     3. 更新到最新命令.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Consolas\'; font-size:16pt;\">   </span><span style=\" font-family:\'Consolas\'; font-size:16pt; font-weight:600; font-style:italic;\">V0.1</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Consolas\'; font-size:12pt;\">     1. 读取所有RAM值.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Consolas\'; font-size:12pt;\">     2. 基本命令.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Consolas\'; font-size:12pt;\">     3. 自定义命令.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Consolas\'; font-size:12pt; font-weight:600;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Consolas\'; font-size:16pt; font-weight:600;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Consolas\'; font-size:16pt; font-weight:600;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Consolas\'; font-size:16pt; font-weight:600;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Consolas\'; font-size:16pt; font-weight:600;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Consolas\';\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Consolas\';\"><br /></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "帮助/使用手册"))

import picture_rc
